import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import HeaderNavbar from "@/components/HeaderNavbar"

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Public Administration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
      <HeaderNavbar/>
        {/* <Navbar/> */}
        
        {children}
        </body>
    </html>
  );
}
